export const listJenisSurat = [
  { value: 'permohonan', text: 'Permohonan' },
  { value: 'Undangan', text: 'undangan' },
  { value: 'pemberitahuan', text: 'Pemberitahuan' },
  { value: 'pengumuman', text: 'Pengumuman' },
  { value: 'mandat', text: 'Mandat' },
  { value: 'rekomendasi', text: 'Rekomendasi' },
  { value: 'keterangan', text: 'Keterangan' },
  { value: 'penugasan', text: 'Penugasan' },
  { value: 'ucapan', text: 'Ucapan' },
  { value: 'memo', text: 'Memo' },
  { value: 'nota', text: 'Nota' },
  { value: 'peringatan', text: 'Peringatan' },
  { value: 'pernyataan', text: 'Pernyataan' },
  { value: 'perjanjian', text: 'Perjanjian' },
  { value: 'balasan', text: 'Balasan' },
  { value: 'keputusan', text: 'Surat Keputusan' },
]

export const listPengirim = [
  { value: 'presiden/wakil', text: 'Presiden / Wakil Presiden' },
  { value: 'sekjen', text: 'Sekretaris Jenderal' },
  { value: 'psdi', text: 'Kementrian Pengembangan Sumber Daya Internal' },
  { value: 'psdm', text: 'Kementrian Pengembangan Sumber Daya Manusia' },
  { value: 'perhub', text: 'Kementrian Perhubungan' },
  { value: 'k2p', text: 'K2P' },
  { value: 'sosling', text: 'Kementrian Sosial dan Lingkungan' },
  { value: 'advo', text: 'Kementrian Advokesma' },
  { value: 'kastrat', text: 'Kementrian Kajian dan Aksi Strategis' },
  { value: 'pit', text: 'Biro Pengembangan Informasi dan Teknologi' },
  { value: 'bismit', text: 'Biro Bisnis dan Kemitraan' },
  { value: 'adkeu', text: 'Biro Administrasi dan Keuangan' },
  { value: 'medinkraf', text: 'Biro Media dan Kreatif' },
]